### ISSUE TITLE
Require .hdf5 files

### ISSUE THREAD

**Issue by Ankit110287** [Scientific-Computing-Lab/MLography#1]
Hi Sir,

I am working on microstructures for dissimilar welds and I came across your work and found that you have uploaded the code on GitHub. Can you please provide the following *.hdf5 files : 'mlography_segment.hdf5', 'preprocessed_imgs.hdf5', 'grains_128.hdf5'.
It will save a lot of time for me.

Thanks

**Comment by matanr** [comment]
Hi,

Attached all required models for segmentation and for anomaly detection ('preprocessed_imgs.hdf5', 'grains_128.hdf5', 'ae_model_blank_label.h5'):
[https://drive.google.com/drive/folders/1YkUAyFW5CfgiVs7e7pL5S3TX7RloesVh?usp=sharing](url)
